{"name": "test_successful_auth_and_token_usage", "status": "failed", "statusDetails": {"message": "AssertionError: Токен не получен в ответе\nassert None is not None", "trace": "tests/api/test_login_token.py:31: in test_successful_auth_and_token_usage\n    assert token is not None, \"Токен не получен в ответе\"\nE   AssertionError: Токен не получен в ответе\nE   assert None is not None"}, "start": 1745166862560, "stop": 1745166863206, "uuid": "9a509d68-1017-4a17-a5d2-3a0142e18725", "historyId": "9832d042f1b1a9b8d065980084a1d460", "testCaseId": "9832d042f1b1a9b8d065980084a1d460", "fullName": "tests.api.test_login_token#test_successful_auth_and_token_usage", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_login_token"}, {"name": "host", "value": "MacBook-Pro-macbook.local"}, {"name": "thread", "value": "81429-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_login_token"}]}